# Generated by Django 4.0.2 on 2022-02-28 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subcategorymodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='category',
        ),
    ]
