# Generated by Django 4.0.2 on 2022-03-14 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_coursemodel_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUsModel',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='price',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='topic_file'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sections', to='app.coursemodel'),
        ),
    ]
