# Generated by Django 4.0.2 on 2022-03-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnermodel',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
