# Generated by Django 4.0.2 on 2022-02-28 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='is_verified',
        ),
    ]
